//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BidCube.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_History
    {
        public int ID { get; set; }
        public System.Guid MCREF { get; set; }
        public string bid_status { get; set; }
        public string reply_status { get; set; }
        public string won_status { get; set; }
        public Nullable<System.DateTime> valid_from { get; set; }
        public Nullable<System.DateTime> valid_to { get; set; }
    }
}
